version: '3.3'
services:
  livethinkcode:
    build:
      context: .
    ports:
      - '3000:80'
    environment:
      GithubClientID: '${GithubClientID}'
      GithubClientSecret: '${GithubClientSecret}'
      DBConnectionString: '${DBConnectionString}'
    networks:
      - ltc

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - ltc

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080
    networks:
      - ltc

networks:
  ltc:
    external: false