version: '3.3'
services:
  livethinkcode:
    build:
      context: .
    ports:
      - '3000:80'
    environment:
      GithubClientID: '${GithubClientID}'
      GithubClientSecret: '${GithubClientSecret}'
      DBConnectionString: '${DBConnectionString}'